;;; init.el --- emacs-cpp: a CLion-like C++ environment  -*- lexical-binding: t; -*-

;;; Commentary:

;; Loaded through the symlink ~/.emacs.d/init.el (D-003).  The repository root is
;; found from this file's true name, so lib/ and lisp/ resolve inside the repository
;; while `user-emacs-directory' (history, bookmarks, caches) stays ~/.emacs.d/.

;;; Code:

(defconst emacs-cpp-root
  (file-name-directory (file-truename (or load-file-name buffer-file-name)))
  "Root of the emacs-cpp repository.")

;; Generated by `make packages' (DESIGN 12).  Missing means the packages were never
;; built: stop with the fix instead of starting half-configured (DESIGN 4).
(let ((load-path-file (expand-file-name "lib/load-path.el" emacs-cpp-root)))
  (unless (file-exists-p load-path-file)
    (error "emacs-cpp: %s is missing; run `make packages' in %s"
           load-path-file emacs-cpp-root))
  (load load-path-file nil t)
  (load (expand-file-name "lib/autoloads.el" emacs-cpp-root) nil t))

(add-to-list 'load-path (expand-file-name "lisp" emacs-cpp-root))

;; Customize writes outside the repository (D-003).
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))

;; Every package is deferred unless its form says otherwise (DESIGN 11), and an error
;; in a form stops startup instead of becoming a warning (DESIGN 5).
(require 'use-package)
(setq use-package-always-defer t
      use-package-expand-minimally t)

;; Defaults that differ by platform, one file each (D-055), before the modules that
;; use them.  An unknown platform stops here instead of starting half-configured.
(defun emacs-cpp-defaults-feature (platform)
  "Return the defaults feature for PLATFORM, a `system-type' value (D-055)."
  (pcase platform
    ('gnu/linux 'defaults-gnu-linux)
    ('darwin 'defaults-darwin)
    (_ (error "emacs-cpp: no defaults file for platform %s (D-055)" platform))))
(require (emacs-cpp-defaults-feature system-type))

;; Module order is the contract (DESIGN 5): a module may only use modules above it.
(require 'init-ui)
(require 'init-completion)
(require 'init-project)
(require 'init-cpp)
(require 'init-cmake)
(require 'init-debug)
(require 'init-python)
(require 'init-git)
(require 'init-writing)

(when (file-exists-p custom-file)
  (load custom-file nil t))

;;; init.el ends here
